# Stage 09 — Homework Notebook

In the lecture, we learned how to create engineered features. Now it’s your turn to apply those ideas to your own project data.

In [12]:
import os, pathlib
import pandas as pd
import numpy as np
from pathlib import Path


DATA = pathlib.Path( '../data')
DATA.mkdir(parents=True, exist_ok=True)

df = pd.read_parquet(DATA / "citibike_cleaned.parquet")

df.head()

               name  bikes  free           timestamp        date
0  1 Ave & E 110 St      0     0 2024-11-01 15:13:29  2024-11-01
1  1 Ave & E 110 St      0    25 2024-11-04 03:39:33  2024-11-04
2  1 Ave & E 110 St     12    13 2024-11-04 23:45:58  2024-11-04
3  1 Ave & E 110 St     14    11 2024-11-05 00:03:57  2024-11-05
4  1 Ave & E 110 St      6    19 2024-11-05 23:51:18  2024-11-05

## Implement total spots

In [13]:
df['total_spot'] = df['bikes'] + df['free']
df.head()

               name  bikes  free           timestamp        date  total_spot
0  1 Ave & E 110 St      0     0 2024-11-01 15:13:29  2024-11-01           0
1  1 Ave & E 110 St      0    25 2024-11-04 03:39:33  2024-11-04          25
2  1 Ave & E 110 St     12    13 2024-11-04 23:45:58  2024-11-04          25
3  1 Ave & E 110 St     14    11 2024-11-05 00:03:57  2024-11-05          25
4  1 Ave & E 110 St      6    19 2024-11-05 23:51:18  2024-11-05          25

### Total_spot
Is mostly useful to see if the data is healthy because if at some point the total spot value changes, it means that something is off, parking spots cant appear or desappear out of thin air

In [14]:
roll_7d = (
    df.groupby('name')
      .rolling('7D', on='timestamp')['bikes']
      .mean()
      .reset_index(level=0, drop=True)
)

df['bikes_roll_7d'] = roll_7d.to_numpy()

df.head()

,name,bikes,free,timestamp,date,total_spot,bikes_roll_7d
0,1 Ave & E 110 St,0,0,2024-11-01 15:13:29,2024-11-01,0,0.0
1,1 Ave & E 110 St,0,25,2024-11-04 03:39:33,2024-11-04,25,0.0
2,1 Ave & E 110 St,12,13,2024-11-04 23:45:58,2024-11-04,25,4.0
3,1 Ave & E 110 St,14,11,2024-11-05 00:03:57,2024-11-05,25,6.5
4,1 Ave & E 110 St,6,19,2024-11-05 23:51:18,2024-11-05,25,6.4

### Bikes rolling mean over a week
To see the trend over time and not only the week day vs weekend trend